name: AST CxONE Scan
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main
        with:
          project_name: cx-ricardo-puga/NodeGoat
          cx_tenant: sca-jasper-dev-mt
          base_uri: https://app-rpuga-test-wi.dev.cxast.net/
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          additional_params: --tags SCA --scan-types 'sca,iac-security'
